version: '3.9'

services:
  app:
    build: .
    container_name: painaway-app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=painaway
      - DB_SSLMODE=disable
    ports:
      - "8080:8080"

  db:
    image: postgres:16
    container_name: painaway-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: painaway
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
